apiVersion: apps/v1
kind: Deployment
metadata:
  name: jquery
  namespace: jquery
spec:
  selector:
    matchLabels:
      app: app-jquery
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: app-jquery
    spec:
      containers:
      - name: jquery
        image: 275630824768.dkr.ecr.us-east-2.amazonaws.com/jquery-eks:7
        ports:
        - containerPort: 80